kind = "DojoModel"
class_hash = "0x16f9f644d58ce1c8eb32b2e41b09ba9d7fdf86793a6f76e28fc67819730a052"
original_class_hash = "0x16f9f644d58ce1c8eb32b2e41b09ba9d7fdf86793a6f76e28fc67819730a052"
abi = "manifests/dev/abis/base/models/dojo_starter_models_position_position.json"
name = "dojo_starter::models::position::position"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
