kind = "DojoModel"
class_hash = "0x4d389f510fc5b9f57c583ba03167e428fead24ceead6907d5cd16aeab8bd434"
original_class_hash = "0x4d389f510fc5b9f57c583ba03167e428fead24ceead6907d5cd16aeab8bd434"
abi = "manifests/dev/abis/base/models/dojo_starter_models_path_path.json"
name = "dojo_starter::models::path::path"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "tiles"
type = "Array<u32>"
key = false

[[members]]
name = "end_time"
type = "u64"
key = false

[[members]]
name = "completed"
type = "bool"
key = false
