kind = "DojoModel"
class_hash = "0x26fbc68defa59f89209e1906b98940323e52c03b4ac611edecd6aba5e7bb427"
original_class_hash = "0x26fbc68defa59f89209e1906b98940323e52c03b4ac611edecd6aba5e7bb427"
abi = "manifests/dev/abis/base/models/dojo_starter_models_path_path.json"
name = "dojo_starter::models::path::path"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "tiles"
type = "Option<Span<Vec2>>"
key = false

[[members]]
name = "end_time"
type = "Option<u64>"
key = false
