name = "dojo_starter::systems::actions::actions"
reads = []
writes = ["Position", "Moves", "DirectionsAvailable", "Tile", "ActivePath", "WorldSettings", "WorldPendingPaths", "PendingPath"]
init_calldata = []
