[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0xb4079627ebab1cd3cf9fd075dda1ad2454a7a448bf659591f259efa2519b18"
transaction_hash = "0x3a729aa09b4ad351fbc724f94c6d599037a53d7d9b5a182097a60fb09d0486c"
block_number = 14
seed = "dojo_starter"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x3610b797baec740e2fa25ae90b4a57d92b04f48a1fdbae1ae203eaf9723c1a0"
class_hash = "0x103db33e83aa4cd2fc67120e2ffcfd36428da45ea1b7064d4a81863225d9d58"
original_class_hash = "0x103db33e83aa4cd2fc67120e2ffcfd36428da45ea1b7064d4a81863225d9d58"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = [
    "Position",
    "Moves",
    "DirectionsAvailable",
    "Tile",
    "Path",
    "WorldSettings",
    "WorldPendingPaths",
    "PendingPath",
]
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x13fc796dd2d767ca4051ee20d673074f74b6e6b072bef1926ba429e427c8080"
original_class_hash = "0x13fc796dd2d767ca4051ee20d673074f74b6e6b072bef1926ba429e427c8080"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_moves_directions_available.json"
name = "dojo_starter::models::moves::directions_available"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "directions"
type = "Array<Direction>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xe7bc1a9ccd3ada6130fcdae0ca9959c100574e1dc6304567732d147c3c323d"
original_class_hash = "0xe7bc1a9ccd3ada6130fcdae0ca9959c100574e1dc6304567732d147c3c323d"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_moves_moves.json"
name = "dojo_starter::models::moves::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models.members]]
name = "can_move"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1bd1c9409571a759e98db15ecdd862c10d365fd68b9a79b7f132e13ad04a80b"
original_class_hash = "0x1bd1c9409571a759e98db15ecdd862c10d365fd68b9a79b7f132e13ad04a80b"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_path_path.json"
name = "dojo_starter::models::path::path"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "tiles"
type = "Array<u32>"
key = false

[[models.members]]
name = "end_time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x309cb4ab77a059e0505993143322ed53f6862bb6715745cc25c642b8c470805"
original_class_hash = "0x309cb4ab77a059e0505993143322ed53f6862bb6715745cc25c642b8c470805"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_pending_paths_pending_path.json"
name = "dojo_starter::models::pending_paths::pending_path"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "path"
type = "Option<Span<Vec2>>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7ac36ee4d932c81e45218f0657190fd735c87cebd9acff654e86f11ff9224cc"
original_class_hash = "0x7ac36ee4d932c81e45218f0657190fd735c87cebd9acff654e86f11ff9224cc"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_pending_paths_world_pending_paths.json"
name = "dojo_starter::models::pending_paths::world_pending_paths"

[[models.members]]
name = "paths_id"
type = "u32"
key = true

[[models.members]]
name = "pending_paths"
type = "Array<ContractAddress>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x16f9f644d58ce1c8eb32b2e41b09ba9d7fdf86793a6f76e28fc67819730a052"
original_class_hash = "0x16f9f644d58ce1c8eb32b2e41b09ba9d7fdf86793a6f76e28fc67819730a052"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_position_position.json"
name = "dojo_starter::models::position::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3f08e80f7dbdd85355bc45b663b06aab29ee7c555343f0f50032a9460b109e2"
original_class_hash = "0x3f08e80f7dbdd85355bc45b663b06aab29ee7c555343f0f50032a9460b109e2"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_tile_tile.json"
name = "dojo_starter::models::tile::tile"

[[models.members]]
name = "_coords"
type = "Vec2"
key = true

[[models.members]]
name = "coords"
type = "Vec2"
key = false

[[models.members]]
name = "nature"
type = "CaseNature"
key = false

[[models.members]]
name = "allocated"
type = "Option<ContractAddress>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x22e95f68b0c997692ea80b6c55efb33b8351f67b23cda5dedbdfa2260d7e852"
original_class_hash = "0x22e95f68b0c997692ea80b6c55efb33b8351f67b23cda5dedbdfa2260d7e852"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_world_settings_world_settings.json"
name = "dojo_starter::models::world_settings::world_settings"

[[models.members]]
name = "settings_id"
type = "u32"
key = true

[[models.members]]
name = "grid_size"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1e1fa676a44c4b22fe024f3d3a681904fc4fcaececd382b94d794593b811de2"
original_class_hash = "0x1e1fa676a44c4b22fe024f3d3a681904fc4fcaececd382b94d794593b811de2"
abi = "manifests/dev/abis/deployments/models/dojo_starter_systems_actions_actions_moved.json"
name = "dojo_starter::systems::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false
