kind = "DojoContract"
class_hash = "0x45cdca9780b08b5cfb582c90ce2e7bad3d3396ef8512251db84d6820485ec45"
original_class_hash = "0x45cdca9780b08b5cfb582c90ce2e7bad3d3396ef8512251db84d6820485ec45"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"
