kind = "DojoContract"
class_hash = "0x6c6535b1ec5f4e8386130666b6343ef65c4a8d0b7a46d59c311a2cebfdc2845"
original_class_hash = "0x6c6535b1ec5f4e8386130666b6343ef65c4a8d0b7a46d59c311a2cebfdc2845"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"
